export const COUNT_CHANGE = 'COUNT_CHANGE';
export const START_TIME_CHANGE = 'START_TIME_CHANGE';
export const STOP_TIME_CHANGE = 'STOP_TIME_CHANGE';
export const CLOCK_COLOR_CHANGE = 'CLOCK_COLOR_CHANGE';
export const BG_COLOR_CHANGE = 'BG_COLOR_CHANGE';